# Generated by Django 3.2.7 on 2021-09-11 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='dept_lect',
        ),
        migrations.AddField(
            model_name='lecturer',
            name='dept_lect',
            field=models.ManyToManyField(to='FirstApp.Deptartment'),
        ),
    ]
