# Generated by Django 3.2.7 on 2021-09-11 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0002_auto_20210911_1139'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deptartment',
            new_name='Department',
        ),
    ]
